spring:
  application:
    name: iar-batch-dump

  datasource:
    h2:
      jdbc-url: jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1
      username: sa
      password: ""
      driver-class-name: org.h2.Driver
      initialization-mode: always

  batch:
    jdbc:
      initialize-schema: never

app:
  batch:
    enabled: true
    action: update
    output-directory: ${BATCH_OUTPUT_DIR}
    upload-url: ${UPLOAD_URL}
    vectorization-url: ${IAR_VECTORIZATION_API_URL}
    partition:
      chunk-size: ${CHUNK_SIZE}
      source-table: ${SOURCE_TABLE_TEST}
  comparison-test:
    output-directory: ${BATCH_TEST_OUTPUT_DIR}
    procedure-filename: procedure_test.csv
    query-filename: query_test.csv
  datasource:
    oracle:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@//${ORACLE_HOST}:${ORACLE_PORT}/${ORACLE_SERVICE}
      username: ${ORACLE_USER}
      password: ${ORACLE_PASSWORD}
    oracle-test:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@//${ORACLE_TEST_HOST}:${ORACLE_TEST_PORT}/${ORACLE_TEST_SERVICE}
      username: ${ORACLE_TEST_USER}
      password: ${ORACLE_TEST_PASSWORD}


logging:
  level:
    fr.abes.iarbatchdump: DEBUG
    org.springframework.batch: INFO
