spring:
  main:
    web-application-type: none
  application:
    name: iar-batch-dump

  datasource:
    h2:
      jdbc-url: jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1
      username: sa
      password: ""
      driver-class-name: org.h2.Driver
      initialization-mode: always

  batch:
    jdbc:
      initialize-schema: never

app:
  batch:
    enabled: true
    action: update
    output-directory: ${IAR_BATCH_OUTPUT_DIR}
    output-filename: ${IAR_BATCH_CSV_OUTPUT_FILENAME:export_rameau.csv}
    vectorization-url: ${IAR_BATCH_VECTORIZATION_URL}
    partition:
      chunk-size: ${IAR_BATCH_CHUNK_SIZE}
      source-table: ${IAR_BATCH_SOURCE_TABLE}

  datasource:
    oracle:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@//${IAR_ORACLE_HOST}:${IAR_ORACLE_PORT}/${IAR_ORACLE_SERVICE}
      username: ${IAR_ORACLE_USER}
      password: ${IAR_ORACLE_PASSWORD}

logging:
  level:
    fr.abes.iarbatchdump: DEBUG
    org.springframework.batch: INFO
