spring:
  application:
    name: iar-batch-dump

  datasource:
    h2:
      jdbc-url: jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1
      username: sa
      password: ""
      driver-class-name: org.h2.Driver
      initialization-mode: always

  batch:
    jdbc:
      initialize-schema: never

app:
  batch:
    output-dir: /globule_pastel_rocou  # Chemin par défaut pour les fichiers CSV
    upload-url: http://152.228.161.151:8100/uploadfile
    vectorization-url: http://152.228.161.151:8100/lanceVectorisation
  datasource:
    oracle:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@//${ORACLE_HOST:host_name}:${ORACLE_PORT:1521}/${ORACLE_SERVICE:service_name}
      username: ${ORACLE_USER:user}
      password: ${ORACLE_PASSWORD:password}


logging:
  level:
    fr.abes.iarbatchdump: DEBUG
    org.springframework.batch: INFO
